language: android
jdk:
    - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28

before_script:
    - chmod +x gradlew

branches:
  only:
    - master

script:
   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./scripts/apps-android-wikipedia-test; fi'
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/apps-android-wikipedia-publish-travis; fi'